### ISSUE TITLE
tailwindcss-module isnt compatible

### ISSUE THREAD

**Issue by arafays** [fandogh/hapi-nuxt#60]
### Version

[v3.0.0](https://github.com/hapi-nuxt/releases/tag/v3.0.0)

### Reproduction link

[https://codesandbox.io/s/quirky-rgb-v8jlr?file=/server.js](https://codesandbox.io/s/quirky-rgb-v8jlr?file=/server.js)

### Steps to reproduce

```
yarn nuxt
```

Runs and renders correctly loading tailwindcss module and everything works fine

```
node server.js
```
Runs and purges all tailwindcss and ignoring the config files.

### What is expected ?

`yarn nuxt` renders the tailwind without a problem

`node server.js` compiles and runs

### What is actually happening?

both should have the same behaviour as it is a plugin that shouldnt require any extra config

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hapi-nuxt/issues/c22">#c22</a>)</em></sub></div>

**Comment by arafays** [comment]
This can also be replicated using v2.3.0

**Comment by atinux** [comment]
This is why we are deprecating using Nuxt as middleware, it leads to too many issues.

Can you take a look at https://github.com/nuxt-community/express-template and how we implemented Express as a Nuxt serverMiddleware?

**Comment by pi0** [comment]
@Atinux Although programmatic usage of nuxt is not recommanded, i think this is in tailwind module scope to make a warning about incompatibility or fix issue (since is not hapi specific i guess)

Also despite express, hapi cannot directly be used as a serverMiddleware with connect stack (at least in a non-hacky way).

@arafays I'm closing this issue since there is not any action point on behalf of this integration plugin. Feel free making issue either for nuxt/nuxt.js or nuxt-community/tailwindcss-module for programmatic usage.
