### ISSUE TITLE
Audience for plugin and is this now deprecated?

### ISSUE THREAD

**Issue by jameswragg** [fandogh/hapi-nuxt#63]
Really pleased to see this plugin as Hapi.js has to be one of, if not the most secure & manageable HTTP frameworks out there but I have 2 questions:

1. I was a little confused to see [this comment](https://github.com/nuxt/create-nuxt-app/issues/563#issuecomment-656611288) from @pi0 in July 2020 saying it was deprecated. Why is that? Is there a new plugin/interface or is Nuxt.js moving away from framework integrations?
2. Some of hapi's strengths is it's payload validation & authentication, so why [disable it](https://github.com/nuxt-community/hapi-nuxt/blob/master/lib/plugin.js#L36)? If I'm understanding this plugin correctly it creates a catch-all route mostly by-passing hapi configuration & forwards on to the Nuxt renderer. Which makes me wonder, is there a specific setup this plugin is designed for?

Thanks in advance.

**Comment by pi0** [comment]
Hi @jameswragg. Sorry for the confusion. Actually as mentioned in the linked comment, programmatic usage (and using with other frameworks is **not** deprecated) but not recommended and left for advanced users because of its edge cases. (that's why not included in CNA template anymore).

Starting with nuxt3 release, a new build system (nitro) will allow easier integration with frameworks but until then, it would be probably easier to create separate API and SSR applications and deploy them separately (unless hapi plugin works for you)

Regarding 2, not really sure what was the reason as it was a long time ago I was using hapi. But if it doesn't break basic setup, feel free to open a PR to change its value.

**Comment by jameswragg** [comment]
Thanks for clarifying @pi0
